linters-settings:
  lll:
    line-length: 140
  gosec:
    # complains that we allow to bypass checking certificates/keys
    excludes:
      - G402
      - G106
  gomnd:
    ignored-functions:
      - strings.SplitN
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - "github.com/dmacvicar/terraform-provider-libvirt"
          - "github.com/community-terraform-providers/terraform-provider-ignition/v2"
          - "github.com/digitalocean/go-libvirt"
          - "libvirt.org/go/libvirtxml"
          - "github.com/davecgh/go-spew"
          - "github.com/google/uuid"
          - "github.com/hashicorp/terraform-plugin-sdk/v2"
          - "github.com/hooklift/iso9660"
          - "github.com/mattn/goveralls"
          - "github.com/stretchr/testify"
          - "golang.org/x/crypto"
          - "golang.org/x/lint"
  revive:
    rules:
      - name: unused-parameter
        disabled: true

linters:
  enable-all: false
  enable:
    - unparam
    - exhaustive
    - godot
    - nilerr
    - gosec
    - revive
    - gocritic
    - misspell
    - lll
    - errorlint
    - errcheck
    - gomnd
    - nolintlint

issues:
  exclude-rules:
    - text: "Error return value of `d.Set` is not checked"
      linters:
        - errcheck
    - text: "Magic number: 1024, in <argument> detected"
      linters:
        - gomnd
    - text: "ifElseChain: rewrite if-else to switch statement"
      linters:
        - gocritic
    - text: "should check returned error before deferring file.Close()"
      linters:
        - staticcheck
    - path: '(.+)_test\.go'
      linters:
        - lll
