linters-settings:
  lll:
    line-length: 140
  gosec:
    # complains that we allow to bypass checking certificates/keys
    excludes:
      - G402
      - G106
  gomnd:
    ignored-functions:
      - strings.SplitN

linters:
  enable-all: false
  enable:
    - ifshort
    - unparam
    - exhaustive
    - godot
    - nilerr
    - gosec
    - revive
    - gocritic
    - misspell
    - depguard
    - lll
    - errorlint
    - errcheck
    - gomnd
    - nolintlint

issues:
  exclude-rules:
    - text: "Error return value of `d.Set` is not checked"
      linters:
        - errcheck
    - text: "Magic number: 1024, in <argument> detected"
      linters:
        - gomnd
    - text: "ifElseChain: rewrite if-else to switch statement"
      linters:
        - gocritic
    - text: "should check returned error before deferring file.Close()"
      linters:
        - staticcheck
    - path: '(.+)_test\.go'
      linters:
        - lll
