os: osx
osx_image: xcode9.1
language: go

go:
  - 1.9
go_import_path: github.com/dmacvicar/terraform-provider-libvirt
install: true
before_script:
  - brew install qemu
  - brew install libvirt
  - bash travis/setup-guest-darwin
script:
  - make testacc
